include(
    "adapter:memory",
    "adapter:oauth",
    "adapter:rdb",
    "app:api",
    "app:support:auth",
    "app:support:exception",
    "app:websocket",
    "domain",
    "core",
    "support:jwt",
    "support:logging",
    "support:yaml",
)
