management:
    endpoints:
        web:
            exposure:
                include: prometheus
    endpoint:
        prometheus:
            enabled: true
#    metrics:
#        tags:
#            application: ${spring.application.name}
