name: Continuous Integration

on:
    pull_request:
        branches:
            - 'main'
            - 'develop'
            - 'feature/*'
            - 'fix/*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Check ktlint format
                run: ./gradlew ktlintCheck

            -   name: Gradle Clean & Build
                run: ./gradlew clean build

            -   name: Test with Gradle
                run: ./gradlew test

            -   name: Upload CI results
                uses: actions/upload-artifact@v4
                with:
                    name: ci-results
                    path: build/ci-results
